version: "3.8"

services:
  # MQTT broker service
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  # MongoDB database service
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  # Backend API server service
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/utopiatech
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
      - PORT=5000
      - NODE_ENV=development
      
    depends_on:
      - db
      - mqtt-broker
    restart: always

  # MQTT worker service
  mqtt-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mqtt-worker
    command: ["node", "workers/mqttWorker.js"]
    environment:
      - MONGO_URI=mongodb://db:27017/utopiatech
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    depends_on:
      - db
      - mqtt-broker
    restart: always

  # IoT simulator service
  simulator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iot-simulator
    command: ["node", "simulators/simulator.js"]
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    depends_on:
      - mqtt-broker
    restart: always

volumes:
  mongodb_data:
